language: node_js
node_js:
- '6'
sudo: false
after_success:
- ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: HyvA8wLP2tzFJfzXfYY1jVbK8KG20Uhw5DAdDCQ8x9NaNTzBeAMCPbwn7ufswrGVkGsUY1Epvokb536oIjQpQrjptf2DJljjhARsANtiqFNDdKVWCB+Oxy8emBEpn3bYZtEY6THPnxHJr3Rlz0J/jgJq5h9uzfQ4GVEAwiuKNiI=
  on:
    tags: true
    repo: noflo/noflo-runtime-websocket
